# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "DarlingHQ"
license = "MIT"
licenselink = "https://github.com/darlinghq/www.darlinghq.org/blob/master/LICENSE"
description = "A translation layer that lets you run macOS software on Linux"
homepage = "https://www.darlinghq.org/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
